### ISSUE TITLE
svn Error

### ISSUE THREAD

**Issue by nikitul** [russplaysguitar/CouchDB-for-Coldfusion#4]
I use svn at work. My SVN version is 1.8.5.

When I tried to get CouchDB-for-Coldfusion with svn, I've got this error:

``` text
Added: <path_to>\CouchDBtest\trunk\examples\couchdb_blog\readme.txt  
Added: <path_to>\CouchDBtest\trunk\examples\simple_examples  
Error: Failed to add directory  
Error:  '<path_to>\CouchDBtest\trunk\examples\simple_examples\.svn': object of the same  
Error:  name as the administrative directory  
```

I know this is not an programming error, but because of this error, the only way to get the entire repository is to download it.

I appreciate your work.
Thank You

**Comment by russplaysguitar** [comment]
Thanks for reporting the issue. I've fixed it in: 02dd8535fd7f90359944075b1d2846b9253f7ab8. It must've been broken since I migrated to GitHub (years ago).

**Comment by nikitul** [comment]
No problem. :)
You are lucky. 
I am a newbie as a GitHub user and I suffer a lot.

**Comment by nikitul** [comment]
If my memory is good, I also noticed that the riaforge version is not up to date, but I don't know to tell you in wich files are the differences .
